In [2]:
import torch
import gym
from torch import nn

In [3]:
env = gym.make('CartPole-v1')

In [4]:
int(env.observation_space.shape[0])

4

In [5]:
env.action_space.n

2

In [6]:
state,_  = env.reset()

In [7]:
env.step(1)

c:\Users\Rajath\anaconda3\envs\RL\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(array([ 0.04459925,  0.15985754, -0.0017035 , -0.25188732], dtype=float32),
 1.0,
 False,
 False,
 {})

In [8]:
import numpy as np

# Define data points
xp = [1, 2, 3, 4, 5]
fp = [10, 20, 30, 40, 50]

# Interpolate values at specific x-coordinates, including 5.5
x_values = [1.5, 2.5, 3.5, 6]
interpolated_values = np.interp(x_values, xp, fp)

print(interpolated_values)  # Output: [15. 25. 35. 45.]

[15. 25. 35. 50.]


In [9]:
np.arange(env.action_space.n)

array([0, 1])

In [10]:
np.random.uniform(0,1)

0.9757620981777831

In [11]:
np.random.uniform()

0.045554043540005695

In [12]:
class Network(nn.Module):

    def __init__(self, env):
        super().__init__()
        
        in_features = int(env.observation_space.shape[0])
        
        self.Net = nn.Sequential(
                    nn.Linear(in_features, 65),
                    nn.Tanh(),
                    nn.Linear(65, env.action_space.n)
        )
        
    def forward(self, x):
        return self.Net(x)
    

In [13]:
Q_net = Network(env)

In [14]:
state,_ = env.reset()
torch.tensor(state).unsqueeze(0)

tensor([[-0.0440, -0.0160,  0.0197, -0.0158]])

In [15]:
TT = Q_net(torch.tensor(state).unsqueeze(0))
TT

tensor([[ 0.0641, -0.1459]], grad_fn=<AddmmBackward0>)

In [16]:
t = torch.argmax(Q_net(torch.tensor(state)))

In [17]:
t

tensor(0)

In [18]:
TT.max()

tensor(0.0641, grad_fn=<MaxBackward1>)

In [19]:
state

array([-0.04401108, -0.01603162,  0.01966599, -0.01582484], dtype=float32)

In [20]:
env.step(1)

(array([-0.04433171,  0.17880285,  0.01934949, -0.3022386 ], dtype=float32),
 1.0,
 False,
 False,
 {})

In [21]:
TE = torch.tensor([[-0.0175,  0.0346],
        [-0.0855, -0.0032],
        [-0.0873,  0.0189],
        [-0.0652,  0.0404],
        [-0.1794, -0.1737],
        [-0.0953, -0.0107]],dtype = torch.float32)

In [22]:
TE.max(dim=1,keepdim = True)[0]

tensor([[ 0.0346],
        [-0.0032],
        [ 0.0189],
        [ 0.0404],
        [-0.1737],
        [-0.0107]])

In [24]:
r = torch.tensor([4,5,6])
r.unsqueeze(1)

tensor([[4],
        [5],
        [6]])

In [29]:
np.random.choice(np.arange(2))

1

In [39]:
env = gym.make('CartPole-v0')
env.reset()

for i in range(1000):
    env.step(env.action_space.sample())
    env.render()